src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/CurseRandomGearEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/DowngradeRandomGearEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/EnchantRandomGearEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/UpgradeRandomGearEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

4 more effects, i plan to add even more <(￣︶￣)>

[feat] Upgrade, Downgrade, Curse, Enchant Random Gear

---

src/main/java/me/juancarloscp52/entropy/client/Screens/Widgets/EntropyEventListWidget.java

Didn't test other languages besides English

Sorted Events List

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/ZeusUltEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

Zeus ult is dota 2 reference.
Event will create lightning bolt at top most block in the world of player position.

ZEUS ULT! event

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/VexAttackEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

Event that spawn 1-4 vexes around the player

Vex Attack Event

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/InvisibleEveryoneEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/InvisibleHostileMobsEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/InvisiblePlayerEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

1. Make Player to be invisible
2. Make all hostile mobs to be invisible
3. Make everyone to be invisible

Invisibility Events

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/DeathSightEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/GlassSightEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/GravitySightEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/MiningSightEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/VoidSightEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

1. Gravity Sight - entities that player looking at will be pulled to the player
2. Death Sight - living entities that player looking at will take damage
3. Glass Sight - block that player looking at will be converted into glass
4. Void Sight - block that player looking at will be converted into air
5. Mining Sight - block that player looking at will be mined (break() with drop true)

Sight events

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/TrueFrostWalkerEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

Event will replace water to blue ice underneath player feets. Also will replace lava to magma blocks.

True Frost Walker Event

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/SkyBlockEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

Event that create 2 islands from classic SkyBlock map

SkyBlock Event

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/MidasTouchEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

Event will convert nearby blocks to gold blocks, kill mobs and spawn gold, replace items that player hold and wear to golden ones.
I was debating should i convert whole player`s inventory but i though it would be too brutal so only items that player is holding.

Midas Touch Event

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/BulldozeEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_ar.json
src/main/resources/assets/entropy/lang/es_cl.json
src/main/resources/assets/entropy/lang/es_ec.json
src/main/resources/assets/entropy/lang/es_es.json
src/main/resources/assets/entropy/lang/es_mx.json
src/main/resources/assets/entropy/lang/es_uy.json
src/main/resources/assets/entropy/lang/es_ve.json

Event that breaks blocks around the player

Bulldoze Event

---

README.md

The example added is to a youtuber and twitch streamer DarkViperAU.

Add another youtube example

---

src/main/java/me/juancarloscp52/entropy/client/VotingClient.java
src/main/java/me/juancarloscp52/entropy/client/integrations/discord/DiscordEventListener.java
src/main/java/me/juancarloscp52/entropy/client/integrations/twitch/TwitchIntegrations.java
src/main/java/me/juancarloscp52/entropy/client/integrations/youtube/YoutubeIntegrations.java

Users can no longer vote for the same effect multiple times or vote for multiple effects. Now when user votes for same effect his vote will not count or if user will vote for different effect his vote will be changed to a new effect.

Fix user voting multiple times for same effect

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/AddHeartEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/RemoveHeartEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

Events that will add or remove 1 heart from the player's maximum number of hearts. Changes will be reset when the player dies.

Add/Remove Heart Events

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/RaidEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_ar.json
src/main/resources/assets/entropy/lang/es_cl.json
src/main/resources/assets/entropy/lang/es_ec.json
src/main/resources/assets/entropy/lang/es_es.json
src/main/resources/assets/entropy/lang/es_mx.json
src/main/resources/assets/entropy/lang/es_uy.json
src/main/resources/assets/entropy/lang/es_ve.json

A villager spawns on top of a lectern. Then BAD OMEN 5 is applied to the player and a raid starts.
The raid finishes when the villager is killed, which happens fast if the player does not protect it.

🆕 Raid event

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/ArmorCurseEvent.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_ar.json
src/main/resources/assets/entropy/lang/es_cl.json
src/main/resources/assets/entropy/lang/es_ec.json
src/main/resources/assets/entropy/lang/es_es.json
src/main/resources/assets/entropy/lang/es_mx.json
src/main/resources/assets/entropy/lang/es_uy.json
src/main/resources/assets/entropy/lang/es_ve.json

Add curse enchantments to the player : 
- Curse of Binding to the armor
- Curse of Vanishing to all other items in the inventory

🆕 Curse Binding and Vanishing

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/NoiseMachineEvent.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_ar.json
src/main/resources/assets/entropy/lang/es_cl.json
src/main/resources/assets/entropy/lang/es_ec.json
src/main/resources/assets/entropy/lang/es_es.json
src/main/resources/assets/entropy/lang/es_mx.json
src/main/resources/assets/entropy/lang/es_uy.json
src/main/resources/assets/entropy/lang/es_ve.json

This event spawns a noise machine encased in obsidian above the player. Bedrock or end portal (frame) blocks will prevent the noise machine from spawning.

Add Noise Machine Event

---

src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json

adds translations for new events

Add German translations

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/LagEvent.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json

To "emulate" lag, this event first saves each player's position, and then, after a random number of ticks, teleports every player back to that position. This is repeated until time runs out.

Add Lag Event

---

src/main/java/me/juancarloscp52/entropy/Variables.java
src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/ForceHorseRidingEvent.java
src/main/java/me/juancarloscp52/entropy/mixin/EntityMixin.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_es.json

This event makes every player ride a horse for its duration. The horse cannot be dismounted, and players cannot change into a different vehicle.

Add force horse riding event

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/JumpscareEvent.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_es.json

This event simply plays the elder guardian particle effect and sound to each player.

Add jumpscare event

---

.github/workflows/test-runner.yml

Using Fabric Test Runner, automatically builds last push/PR and tests if it runs in fabric server

Add build and fabric server test.

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/CreativeFlightEvent.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_es.json

This event allows players to fly like in creative mode. Players should be cautious towards the end of the event, because once the time is up, they will fall to their demise.

Add creative flight event

---

src/main/java/me/juancarloscp52/entropy/client/ClientEventHandler.java
src/main/java/me/juancarloscp52/entropy/client/Screens/EntropyIntegrationsScreen.java
src/main/java/me/juancarloscp52/entropy/client/integrations/youtube/YoutubeApi.java
src/main/java/me/juancarloscp52/entropy/client/integrations/youtube/YoutubeIntegrations.java
src/main/resources/assets/entropy/lang/en_gb.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_es.json

I have watched 3 live streams that use youtube integration. They all faced the same problem: after about 48 minutes voting stopped working. At first I thought that the token was not updated correctly, i checked the code and found that "access_type":"offline" is missing (i leave it in code just in case), i added it but it didn't help. After logging one of the responses from google api i got this:
```json
{
"error": {
"code": 403,
"message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
"errors": [
{
"message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
"domain": "youtube.quota",
"reason": …
```

An attempt at improving youtube integration

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/NothingEvent.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_ar.json
src/main/resources/assets/entropy/lang/es_cl.json
src/main/resources/assets/entropy/lang/es_ec.json
src/main/resources/assets/entropy/lang/es_es.json
src/main/resources/assets/entropy/lang/es_mx.json
src/main/resources/assets/entropy/lang/es_uy.json
src/main/resources/assets/entropy/lang/es_ve.json

This is basically a cooldown period for the player, so they can catch a longer breath inbetween events before the mayhem restarts. Less experienced players can benefit from this as well.

Add an event that does nothing

---

src/main/java/me/juancarloscp52/entropy/client/Screens/Widgets/EntropyEventListWidget.java

This PR enables checkboxes that have been disabled by Entropy's accessibility mode to be focusable when navigation the screen with a keyboard. The benefit from this is that the tooltip about the event having been disabled can now also show during keyboard navigation, instead of just when hovering over the checkbox with the mouse.

Improve handling of keyboard navigation in event configuration screen

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/SilenceEvent.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_es.json

This event turns off all sounds as well as subtitles for its duration. Blissful...or anxienty inducing?

Add Silence event

---

src/main/java/me/juancarloscp52/entropy/Variables.java
src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/RainbowSheepEverywhereEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/SpawnRainbowSheepEvent.java
src/main/java/me/juancarloscp52/entropy/mixin/SheepWoolFeatureRendererMixin.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_us.json
src/main/resources/assets/entropy/lang/es_ar.json
src/main/resources/assets/entropy/lang/es_cl.json
src/main/resources/assets/entropy/lang/es_ec.json
src/main/resources/assets/entropy/lang/es_es.json
src/main/resources/assets/entropy/lang/es_mx.json
src/main/resources/assets/entropy/lang/es_uy.json
src/main/resources/assets/entropy/lang/es_ve.json
src/main/resources/assets/entropy/lang/zh_cn.json
src/main/resources/entropy.mixins.json

This new event makes every sheep render their wool as if its name was "jeb_", hence the name of the event. The "RainbowSheepEvents" event has been renamed to "SpawnRainbowSheep" so the two events can be better distinguished.

Add event to make all sheep rainbow sheep

---

src/main/java/me/juancarloscp52/entropy/mixin/FogRendererMixin.java

Before: ![](https://i.imgur.com/Qiou9wf.png)
After: ![](https://i.imgur.com/H1nBORA.png)

Adjust fog color while Herobrine event is active

---

gradle.properties
src/main/generated/data/c/tags/item/spawn_eggs.json
src/main/java/me/juancarloscp52/entropy/client/Screens/Widgets/EntropyEventListWidget.java
src/main/java/me/juancarloscp52/entropy/datagen/EntropyItemTagProvider.java
src/main/java/me/juancarloscp52/entropy/mixin/AbstractScrollAreaAccessor.java
src/main/java/me/juancarloscp52/entropy/mixin/KeyboardInputMixin.java
src/main/resources/entropy.mixins.json
src/main/resources/fabric.mod.json

Based on #137. Should be very straight-forward.

Update to 1.21.4

---

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java
src/main/java/me/juancarloscp52/entropy/events/db/BalloonRaceEvent.java
src/main/java/me/juancarloscp52/entropy/events/db/RacingBalloonEvent.java
src/main/resources/assets/entropy/lang/de_at.json
src/main/resources/assets/entropy/lang/de_ch.json
src/main/resources/assets/entropy/lang/de_de.json
src/main/resources/assets/entropy/lang/en_us.json

This event spawns a fast-flying happy ghast with a random harness for each player, and makes them ride it. The ghast is removed after the event duration is over.

Add racing balloon event

---

src/main/generated/data/entropy/tags/block/ignored_by_midas_touch.json
src/main/java/me/juancarloscp52/entropy/datagen/EntropyBlockTagProvider.java

Shouldn't convert fluids to gold.

Fix midas touch killing swimming players
