COPYING, README.md
This would allow GitHub to automatically recognize the license.
=> Move license notice to README

src/main/java/me/juancarloscp52/entropy/events/db/SkyBlockEvent.java
As of minecraft 1.18 mountains can reach Y 256, this fix will move skyblock islands higher
=> Islands Y placements

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/events/db/FlyingMachineEvent.java, src/main/resources/assets/entropy/lang/en_gb.json, src/main/resources/assets/entropy/lang/en_us.json
Event that creates self returning flying machine.
=> Flying Machine Event

src/main/java/me/juancarloscp52/entropy/events/db/CinematicScreenEvent.java
If you set up button to toggle cinematic camera in the Options > Controls you was able to turn off smooth mouse movement while cinematic camera was active. No more.
=> Cinematic Camera Fix 2

src/main/java/me/juancarloscp52/entropy/events/db/SkyBlockEvent.java
Stop riding anything before teleporting to the island in skyblock event
=> SkyBlock Riding Fix

src/main/java/me/juancarloscp52/entropy/Variables.java, src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/events/db/XRayEvent.java, src/main/java/me/juancarloscp52/entropy/mixin/AbstractBlockStateMixin.java, src/main/java/me/juancarloscp52/entropy/mixin/BlockMixin.java, src/main/resources/assets/entropy/lang/en_gb.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/entropy.mixins.json
Make blocks that not ore, mineral blocks, obsidian or bedrock to not render.
Sodium compatible.
I didn't figure out how to make all chunks render. There seems to be some kind of optimization that doesn't display chunks if they are completely surrounded by full blocks.
=> XRay Event

src/main/java/me/juancarloscp52/entropy/client/Screens/EntropyEventConfigurationScreen.java, src/main/java/me/juancarloscp52/entropy/client/Screens/Widgets/EntropyEventListWidget.java, src/main/java/me/juancarloscp52/entropy/mixin/EntryListWidgetAccessor.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json, src/main/resources/entropy.mixins.json
This makes it easier to find the event the user is looking for. The "Enable All" and "Disable All" buttons only apply to the events that are currently shown as per the search. Here's a short showcase:
https://user-images.githubusercontent.com/5149876/211216570-99f76cbc-b443-42fb-863a-b78a4a4667de.mp4
Additionally, I fixed clicking the checkboxes not making a sound. I didn't feel like creating a separate pull request for this, especially because it's within the same screen this PR modifies.
=> Add a simple search bar to the event configuration screen

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/events/db/HauntedChestsEvent.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_gb.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json
The haunted chests event randomly opens and closes chests in the chunks around the player. This is done client side, so one player won't see the same chests open as another one. I figured this would add to the "hauntedness".
Here's a short showcase:
https://user-images.githubusercontent.com/5149876/212045798-2208e306-ed38-4caa-bb5e-001d3238e5a1.mp4
=> Add haunted chests event

src/main/java/me/juancarloscp52/entropy/events/db/HauntedChestsEvent.java
The haunted chests event loads client side classes, which caused the server crashing on startup. This PR fixes that. Sorry about this oversight on my part.
=> Fix server not starting

src/main/java/me/juancarloscp52/entropy/Variables.java, src/main/java/me/juancarloscp52/entropy/client/EntropyClient.java, src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/events/db/BlackAndWhiteEvent.java, src/main/java/me/juancarloscp52/entropy/mixin/GameRendererMixin.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/shaders/post/black_and_white.json
This PR adds an event which turns on a shader that makes everything appear black and white. This also applies to screens, so you won't be able to see colors in your inventory for example. [Without the effect](https://i.imgur.com/NTAFeqo.png) and [with the effect](https://i.imgur.com/O5SCnr8.png) (note that the hotbar is also black and white).
=> Add black and white shader event

src/main/java/me/juancarloscp52/entropy/client/Screens/EntropyEventConfigurationScreen.java, src/main/java/me/juancarloscp52/entropy/client/Screens/Widgets/EntropyEventListWidget.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_es.json
This PR adds a button to the event configuration screen which allows the player to only show events that are enabled, or only ones that are disabled. If a search term is entered, the button only operates on the displayed events.
Another small change is setting the search bar to automatically be focused when the screen is opened, so the player can type right away without having to manually select the search bar first. This behavior matches the vanilla singleplayer select world screen.
Here's a short showcase of the new filter button:
https://user-images.githubusercontent.com/5149876/213004857-d42608dd-9819-4c17-ab0b-5be628f41c5c.mp4
=> Add button to events configuration screen for filtering events by whether they are enabled

src/main/java/me/juancarloscp52/entropy/Entropy.java, src/main/java/me/juancarloscp52/entropy/NetworkingConstants.java, src/main/java/me/juancarloscp52/entropy/client/EntropyClient.java, src/main/java/me/juancarloscp52/entropy/server/ServerEventHandler.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json
The command needs operator permission. Any event can be run at any time, even if it is disabled. This is helpful to test events without having to wait for the timer. If an event is run, it will immediately be executed, and its duration is independent of the timer.
I also added a subcommand that removes all events from the display that have ended. This makes it possible to clear the display after having manually run a lot of events, creating room for new ones to properly show up without having to wait for the timer to remove them one by one.
=> Add a command to manually run an event

src/main/java/me/juancarloscp52/entropy/Entropy.java, src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/mixin/MathHelperMixin.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_es.json
The first fix added is another Inject into MathHelper, which now also covers horses, shulker bullets, wither skulls, and jumping dolphins and foxes.
The second fix is disabling the event in singleplayer, as it leads to [faulty worldgen](https://i.imgur.com/dAtlOCN.png) due to the integrated server using the modified MathHelper for worldgen. MathHelperMixin is only applied on clients, so worldgen on a dedicated server is not affected. I chose this solution over creating mixins for all instances where linear interpolation is used in worldgen, because there are a lot of places it is used and it would quickly overwhelm.
If #87 is merged, it may be beneficial to also prevent running of this event via the command in singleplayer.
=> Fixes for the stuttering event

src/main/java/me/juancarloscp52/entropy/client/integrations/twitch/TwitchIntegrations.java
I though that event.getUser().getUserId() will return twitch's user id, appears that it returns UUID for connection to IRC server. It will be different everytime you connect to chat. Viewers able to open multiple chat windows and vote multiple times. This PR fixes that.
=> Twitch vote fix

langGenerator.sh
This PR modifies the previously named `spanishLangGenerator` script to also support German language files `de_at` and `de_ch`. It is renamed to `langGenerator` to reflect that it no longer only generates Spanish files. Additionally, there's a fix to make use of the `list` (now `spanish`) variable and iterate over that array.
=> Support German language files in language script

build.gradle, gradle.properties, src/main/java/me/juancarloscp52/entropy/client/EntropyIntegrationsSettings.java, src/main/java/me/juancarloscp52/entropy/client/Screens/EntropyIntegrationsScreen.java, src/main/java/me/juancarloscp52/entropy/client/VotingClient.java, src/main/java/me/juancarloscp52/entropy/client/websocket/OverlayMessage.java, src/main/java/me/juancarloscp52/entropy/client/websocket/OverlayServer.java, src/main/java/me/juancarloscp52/entropy/client/websocket/OverlayVoteOption.java, src/main/java/me/juancarloscp52/entropy/client/websocket/OverlayWebsocket.java, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json
This allows any of the ChaosModV web socket clients to be used with the mod, so an OBS browser-source can be used to display the upcoming events to chat, rather then displayed to the player/streamer.
An example can be found here: https://www.twitch.tv/videos/1753852677
Note that this does not include the HTML file , only the web socket server to enable a HTML file to be used. I used the ChaosModV format so any streamers who have one for that, don't have to change anything. The default one from gta-chaos-mod/ChaosModV also works
=> feat: Add Websocket server and ability to remove displayed events

build.gradle
I am so sorry, it seems I forgot to add the library to be included when the jar is built fully
=> fix: Add websocket library into build

src/main/java/me/juancarloscp52/entropy/client/Screens/EntropyConfigurationScreen.java
Addresses #108. I chose 3 minutes more or less arbitrarily. It should give a good amount of headroom while not being too long.
=> Increase the maximum base event and timer durations to 180 seconds

src/main/java/me/juancarloscp52/entropy/mixin/MathHelperMixin.java
The new lerp method takes a float and two integers, and returns an integer. It was added in 1.19.4 and is used by display entities. Adding it to the MathHelper mixin means that display entities will now also be affected by the stuttering event.
=> Make StutteringEvent apply to newly added lerp method as well

src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/events/db/HalfHeartedEvent.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json, src/main/resources/assets/entropy/lang/zh_cn.json
Changes made to the one heart event:
- Now called "Half-Hearted". This change was made because it is a popular datapack in the Minecraft community[^1][^2], and also stays more true to the GTAV chaos mod's "One Hit K.O.".
- Health is reduced to half a heart instead of one heart, meaning any damage will kill the player
- When the event ends, each player's health is now restored to the amount it was before the event started. This benefits players as they no longer need to deal with the effects of the event after it has ended.
[^1]: https://www.youtube.com/watch?v=wHaqPL317ZM
[^2]: https://www.speedrun.com/mc_dmce?h=HHH_Any_Glitchless-Random_Seed-1.16&x=7dgxmmpk-jlzr1xy8.rqv77ywq-9l7xq54n.0q5663n1
=> Revamp One Heart event to Half-Hearted

src/main/java/me/juancarloscp52/entropy/client/ClientEventHandler.java
This is a simple change that hides Entropy's overlay when the player is looking at the debug screen that can be activated with F3. Without this, some parts of the debug screen are obscured by Entropy. This behavior is currently not configurable, but if desired such a setting could easily be added.
=> Hide Entropy's overlay when the F3 debug screen is rendered

src/main/java/me/juancarloscp52/entropy/Entropy.java, src/main/java/me/juancarloscp52/entropy/EntropyTags.java, src/main/java/me/juancarloscp52/entropy/client/ConstantColorDustParticle.java, src/main/java/me/juancarloscp52/entropy/client/EntropyClient.java, src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/events/db/RainbowTrailsEvent.java, src/main/java/me/juancarloscp52/entropy/server/ConstantColorDustParticleEffect.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/particles/constant_color_dust.json
This event adds a rainbow particle trail to the back of every entity. This intentionally includes armor stands, arrows, fireballs, and more. A new tag NO_RAINBOW_TRAIL is added to be able to turn the event off for specific entity types.
https://user-images.githubusercontent.com/5149876/227370020-dbccd65b-f0d6-4874-b89d-4b2cfab3e4a6.mp4
=> Add rainbow trails event

src/main/generated/data/entropy/tags/items/midas_touch_golden_items.json, src/main/java/me/juancarloscp52/entropy/EntropyTags.java, src/main/java/me/juancarloscp52/entropy/datagen/EntropyItemTagProvider.java, src/main/java/me/juancarloscp52/entropy/events/db/MidasTouchEvent.java
1. Melons now have a 50% chance of converting to glistering melons. There is no other way to get glistering melons with midas touch, because they cannot be eaten.
2. Added an item tag `entropy:midas_touch_golden_items` that now includes all of the items that were previously stored in the `_goldenItems` list. This tag contains the item tag `minecraft:piglin_loved` and the golden nugget by default. The addition of the piglin_loved tag means that more items are now considered gold by midas touch than before this change. These are: Gilded Blackstone, Light Weighted Pressure Plate, Bell, Clock, and Glistering Melon Slice.
Sidenote unrelated to this PR: When running the data generators, there were more tag file changes than just adding the new item tag. I did not include these changes as they …
=> Make glistering melon available through midas touch and add golden items tag

src/main/java/me/juancarloscp52/entropy/Entropy.java, src/main/java/me/juancarloscp52/entropy/events/EventRegistry.java, src/main/java/me/juancarloscp52/entropy/events/db/ArmorTrimEvent.java, src/main/java/me/juancarloscp52/entropy/server/ServerEventHandler.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json
This PR first and foremost adds a new event that applies a random item trim to every armor item that the player is wearing. Armor that exists only in the player's inventory is not affected. Because armor trims are an experimental feature and locked behind the `update_1_20` datapack, the event is as well. To make this possible, I added a system for locking events behind feature flags. If an event requires a specific feature flag which is not enabled, it cannot be selected in a vote or at random, and it cannot be run manually via the command.
=> Add armor trim event and a system to disable events based on feature flags

src/main/java/me/juancarloscp52/entropy/events/db/SoSweetEvent.java
The original implementation had an issue where the checkerboard would be alternating between different y levels, resulting in it not properly continuing when the bushes were placed across varying-height terrain:
This PR fixes this by only using x/z to get the checkerboard pattern, and then looping through the the Y column from 4 blocks below to 4 blocks above the player to check for placeable positions.
An additional small improvement has been made, moving the creation of the bush block state to a non-static field. This way it is not unnecessarily recreated multiple times (once per iteration) when the event is run.
=> Improve So Sweet! event

src/main/java/me/juancarloscp52/entropy/EntropyUtils.java, src/main/java/me/juancarloscp52/entropy/events/db/LagEvent.java, src/main/java/me/juancarloscp52/entropy/events/db/SkyBlockEvent.java, src/main/java/me/juancarloscp52/entropy/events/db/SkyEvent.java, src/main/java/me/juancarloscp52/entropy/events/db/TeleportHeavenEvent.java
Backported from the upgrade branch, but should work fine in older versions as well. Seems to build at least.
As far as I can tell, the base teleport method in the vanilla game is just broken in this version. The variant used in the to the moon event also didn't actually teleport all of the time, but would sometimes just apply fall damage as if you had teleported. Fun times!
=> Fix teleport events

src/main/java/me/juancarloscp52/entropy/client/ConstantColorDustParticle.java, src/main/java/me/juancarloscp52/entropy/server/ConstantColorDustParticleEffect.java
AbstractDustParticle no longer sets the color, which is why the event broke.
Changes unrelated to the fix:
- Codec used for scale is now the scale codec provided by vanilla
- Switched to using var int for packet codec
=> Fix rainbow trails event

src/main/java/me/juancarloscp52/entropy/client/VotingClient.java
This is a regression introduced in #129.
Previously, the amount of vote options [was written to the new poll packet](https://github.com/juancarloscp52/Entropy/commit/fe8947d9a008e3b2337151596c0c68e921bf386c#diff-adfb677121d4de19f5f2be781b5a81f6aa94cf32cde8369270064c3ee8585472L152-L155) (by default 4; 3 randomly selected events + "random event"), and then [used to check against the total expected amount of options in the vote](https://github.com/juancarloscp52/Entropy/commit/fe8947d9a008e3b2337151596c0c68e921bf386c#diff-4a5378b9ab94af880005aa1d588f9679a6b1854b734fc7325ef6edf7f49a304fL153-L158) after receiving it on the client. In the port to 1.20.6, for de-/serialization of the randomly selected events only their size was written to the packet, and then used to check against the total …
=> Fix integrations not working

src/main/java/me/juancarloscp52/entropy/client/Screens/EntropyEventConfigurationScreen.java, src/main/java/me/juancarloscp52/entropy/client/Screens/Widgets/EntropyEventListWidget.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_gb.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json, src/main/resources/assets/entropy/lang/pt_br.json, src/main/resources/assets/entropy/lang/zh_cn.json
Here are fixes for some bugs that slipped through the cracks:
- The events config screen stopped working properly. It was not possible to re-enable events if they were not disabled by accessibility mode (so the exact opposite of how it should be)
- The language key for the `entropy:hide_events` event was incorrect
=> Fixes for event registry refactor

src/main/java/me/juancarloscp52/entropy/events/Event.java, src/main/java/me/juancarloscp52/entropy/events/db/FakeFakeTeleportEvent.java, src/main/java/me/juancarloscp52/entropy/events/db/FakeTeleportEvent.java, src/main/java/me/juancarloscp52/entropy/server/VotingServer.java, src/main/resources/assets/entropy/lang/de_at.json, src/main/resources/assets/entropy/lang/de_ch.json, src/main/resources/assets/entropy/lang/de_de.json, src/main/resources/assets/entropy/lang/en_us.json, src/main/resources/assets/entropy/lang/es_ar.json, src/main/resources/assets/entropy/lang/es_cl.json, src/main/resources/assets/entropy/lang/es_ec.json, src/main/resources/assets/entropy/lang/es_es.json, src/main/resources/assets/entropy/lang/es_mx.json, src/main/resources/assets/entropy/lang/es_uy.json, src/main/resources/assets/entropy/lang/es_ve.json, src/main/resources/assets/entropy/lang/pt_br.json, src/main/resources/assets/entropy/lang/ru_ru.json
This PR includes two fixes, each in their own commit. Both bugs were likely caused by the changes of #142.
1. Previously, fake teleport events would only say "Fake Teleport" in the vote options. Through the PR, this changed to always showing the underlying teleport event, meaning viewers could not see that the event they were voting for is a fake teleport. This is now changed so the vote contains info about which teleport event is being voted for, and the fact it is a fake one. The event queue now also says that the event was fake, but only after the fact.
2. Because of that PR, the progress bar is rendered for all events that have not ended. This is now amended to include a check for event duration. If the event has not ended and the duration is 0, then there is no progress to be …
=> Fixes for fake teleport events
